name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag escoteirando:$(date +%Y%m%d%H%M)
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: guionardo/escoteirando_fastap/escoteirando
          tag_with_ref: true
